export const SONGS = [
  {
    title: "Koko de Ikiteiru",
    artist: "mary x jon-YAKITORY // Amateurre",
    difficulty: "Mayu's Expert",
    star_rating: 5.42,
    background: require("../Assets/Backgrounds/koko-de-ikiteiru.jpg"),
    audio: new Audio(require("../Assets/Audio/koko-de-ikiteiru.mp3")),
    start_time: 51,
  },
  {
    title: "Tada Koe Hitotsu",
    artist: "Rokudenashi // keevy",
    difficulty: "Expert",
    star_rating: 5.59,
    background: require("../Assets/Backgrounds/tada-koe-hitotsu.png"),
    audio: new Audio(require("../Assets/Audio/tada-koe-hitotsu.mp3")),
    start_time: 93,
  },
  {
    title: "Kimi no Shiranai Monogatari",
    artist: "supercell // monstrata",
    difficulty: "Celestial",
    star_rating: 5.14,
    background: require("../Assets/Backgrounds/kimi-no-shiranai-monogatari.jpg"),
    audio: new Audio(
      require("../Assets/Audio/kimi-no-shiranai-monogatari.mp3")
    ),
    start_time: 239.5,
  },
  {
    title: "GET BACK",
    artist: "THE ORAL CIGARETTES // Nikakis",
    difficulty: "Rolniczy's Insane",
    star_rating: 5.2,
    background: require("../Assets/Backgrounds/get-back.jpg"),
    audio: new Audio(require("../Assets/Audio/get-back.mp3")),
    start_time: 45,
  },
  {
    title: "Asu no Yozora Shoukaihan",
    artist: "Yuaru // Akitoshi",
    difficulty: "Linada's Insane",
    star_rating: 5.2,
    background: require("../Assets/Backgrounds/asu-no-yozora-shokaihan.png"),
    audio: new Audio(require("../Assets/Audio/asu-no-yozora-shokaihan.mp3")),
    start_time: 34.25,
  },
  {
    title: "Endless Tears",
    artist: "CLIFF EDGE feat. Nakamura Maiko // Rakunen",
    difficulty: "AlRakuen's Extra",
    star_rating: 5.21,
    background: require("../Assets/Backgrounds/endless-tears.jpg"),
    audio: new Audio(require("../Assets/Audio/endless-tears.mp3")),
    start_time: 31,
  },
  {
    title: "Flower Dance",
    artist: "DJ OKAWARI // Narcissu",
    difficulty: "Camellia",
    star_rating: 5.22,
    background: require("../Assets/Backgrounds/flower-dance.jpg"),
    audio: new Audio(require("../Assets/Audio/flower-dance.mp3")),
    start_time: 45,
  },
  {
    title: "Blue Zenith",
    artist: "xi // Asphysxia",
    difficulty: "RLC's Insane",
    star_rating: 5.22,
    background: require("../Assets/Backgrounds/blue-zenith.jpg"),
    audio: new Audio(require("../Assets/Audio/blue-zenith.mp3")),
    start_time: 74,
  },
  {
    title: "Zankyo Sanka (TV Size)",
    artist: "Aimer // Sotarks",
    difficulty: "Expert",
    star_rating: 5.27,
    background: require("../Assets/Backgrounds/zankyo-sanka.jpg"),
    audio: new Audio(require("../Assets/Audio/zankyo-sanka.mp3")),
    start_time: 48,
  },
  {
    title: "Utsuroi (Short Ver.)",
    artist: "TrySail // Log Off Now",
    difficulty: "mnyui's Extra",
    star_rating: 5.39,
    background: require("../Assets/Backgrounds/utsuroi-short.jpg"),
    audio: new Audio(require("../Assets/Audio/utsuroi-short.mp3")),
    start_time: 36.5,
  },
  {
    title: "Ano Yume o Nazotte",
    artist: "YOASOBI // Sarawatlism",
    difficulty: "Daisuki",
    star_rating: 5.53,
    background: require("../Assets/Backgrounds/ano-yume-o-nazotte.jpg"),
    audio: new Audio(require("../Assets/Audio/ano-yume-o-nazotte.mp3")),
    start_time: 157.5,
  },
  {
    title: "Kaikai Kitan",
    artist: "Eve // AirinCat",
    difficulty: "FuJu's Expert",
    star_rating: 5.55,
    background: require("../Assets/Backgrounds/kaikai-kitan.png"),
    audio: new Audio(require("../Assets/Audio/kaikai-kitan.mp3")),
    start_time: 48,
  },
  {
    title: "LEVEL <yanaginagi ver.>",
    artist: "yanaginagi x THE SIXTH LIE // Erisu",
    difficulty: "Gaia's Extra",
    star_rating: 5.57,
    background: require("../Assets/Backgrounds/level-yanaginagi-ver.jpg"),
    audio: new Audio(require("../Assets/Audio/level-yanaginagi-ver.mp3")),
    start_time: 164,
  },
  {
    title: "Kani*Do-Luck! (TV Size)",
    artist: "Aiurabu // Azunyan-",
    difficulty: "Extra!",
    star_rating: 5.66,
    background: require("../Assets/Backgrounds/kani-do-luck.jpg"),
    audio: new Audio(require("../Assets/Audio/kani-do-luck.mp3")),
    start_time: 33.5,
  },
  {
    title: "Monochrome Butterfly",
    artist: "Aitsu Nakuru // Sotarks",
    difficulty: "Lami's Extra",
    star_rating: 5.88,
    background: require("../Assets/Backgrounds/monochrome-butterfly.jpg"),
    audio: new Audio(require("../Assets/Audio/monochrome-butterfly.mp3")),
    start_time: 52,
  },
  {
    title: "Literature",
    artist: "Ueda Reina // Kibbleru",
    difficulty: "Promenade",
    star_rating: 5.96,
    background: require("../Assets/Backgrounds/literature.jpg"),
    audio: new Audio(require("../Assets/Audio/literature.mp3")),
    start_time: 52,
  },
];
